### ISSUE TITLE
Presentation without verifiableCredential

### ISSUE THREAD

**Issue by clehner** [w3c/vc-test-suite#112]
The following are negative cases for a `VerifiablePresentation` without `verifiableCredential`:
- `example-8-bad-missing-verifiableCredential.jsonld`
- `example-015-zkp-vp-bad-missing-verifiableCredential.jsonld`

But the [Verifiable Presentation Request Specification](https://github.com/w3c-ccg/vp-request-spec) has an example DID Authentication response which is a `VerifiablePresentation` without a `verifiableCredential`:
https://w3c-ccg.github.io/vp-request-spec/#example-4-a-didauth-response

The Verifiable Credentials Data Model says "If present," about the `verifiableCredential` property of a Presentation, which I think implies that it is optional:
https://w3c.github.io/vc-data-model/#presentations-0

Should `vc-test-suite` be updated to allow a VP without VC?

**Comment by kimdhamilton** [comment]
+1. I agree with your interpretation that the `verifiableCredential` property is optional, and that this is useful for proving control over a DID, as in https://w3c-ccg.github.io/vp-request-spec/#example-4-a-didauth-response
