### ISSUE TITLE
The current Process delegates full authority to the Director in making decision to sign Memoranda of Understanding; the only option for the Membership to disagree is through the appeal process. In particular, the process doesn't call for any prior engagement from the Team with the Membership prior to signing such an MoU.

### ISSUE THREAD

**Issue by lamjay2704** [w3c/vc-test-suite#129]
The current Process delegates full authority to the Director in making decision to sign Memoranda of Understanding; the only option for the Membership to disagree is through the appeal process. In particular, the process doesn't call for any prior engagement from the Team with the Membership prior to signing such an MoU.

As we're moving towards Director-free, and given recent experience where the Membership has indicated interest in greater involvement in these discussions, the Process should probably consider whether having a required advance notice or even a formal AC Review before reaching such a decision would satisfy this need.

__Originally posted by @dontcallmedom in https://github.com/w3c/w3process/issues/606__

**Comment by albertoEnstein** [comment]
Wait
