### ISSUE TITLE
JSON-LD context is Invalid JSON

### ISSUE THREAD

**Issue by yancyribbens** [w3c/vc-test-suite#19]
The context: `https://www.w3.org/2018/credentials/examples/v1` is invalid JSON.  If you paste the context into https://jsonlint.com/ the following parse error occurs:

```
Error: Parse error on line 24:
...			"schema:alumniOf",			"@type": rdf: H
-----------------------^
Expecting ':', got ','
```

**Comment by dmitrizagidulin** [comment]
Thanks @yancyribbens. That needs to be fixed, at w3.org.

(Temporarily, you can find the correct credentials context over at: https://github.com/digitalbazaar/vc-js/blob/master/lib/contexts/vc-examples-v1.js )

**Comment by yancyribbens** [comment]
@dmitrizagidulin thanks that works!

**Comment by dmitrizagidulin** [comment]
(Opened an issue on the vc-data-model repo)

**Comment by burnburn** [comment]
@burnburn to ask @ashimura about status
