### ISSUE TITLE
Should we pass resources to issuers / verifiers?

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-test-suite#2]
The repository contains the resources for the json-ld contexts that are being used.  Nonetheless these aren't supplied to the issuers/verifiers so the issuers/verifiers need to supply those same contexts themselves.

I wonder if we should pass these to the issuers/verifiers or if it isn't worth it.  The only way I can think to do it is to pass a json dictionary like {context-uri: context-filename} as a keyword argument.  But that seems kind of silly?

**Comment by cwebber** [comment]
I guess potentially some issuers/verifiers won't even be using Linked Data Signatures or even paying attention to the documents as graph'y json-ld documents.  So maybe we should just expect applications to ship with these contexts themselves... I dunno?

**Comment by dmitrizagidulin** [comment]
Addressed / no longer applies, closing. Please reopen if it's still an issue.
