### ISSUE TITLE
Test - @context MUST be one or more URIs (negative)

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-test-suite#20]
This test passes for me (I get a green check mark) when I run it with `/bin/cat` as my credential processor (i.e. the test passes when the output is the input).
My assumption is that this should not be the case.
There seem to be two problems here:
1. The test passes even though my processor doesn't return an error
2. The test file `example-1-bad-cardinality.jsonld` seems to have good cardinality (the context URIs are out of order, but there ARE two of them)

**Comment by dmitrizagidulin** [comment]
@brentzundel Both issues are fixed in PR https://github.com/w3c/vc-test-suite/pull/15 - can you try running against that?

**Comment by brentzundel** [comment]
Running against that I get the errors I expected. Any word on when we can merge #15?

**Comment by dmitrizagidulin** [comment]
@brentzundel Not sure. It's ready on my end (I don't have merge rights tho.)

**Comment by brentzundel** [comment]
@msporny this issue can be closed once #15 is merged.

**Comment by msporny** [comment]
PR #15 is merged, closing.
