### ISSUE TITLE
Tests are checking for ISO8601

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-test-suite#22]
The tests for date-time checking are using a regex for ISO8601. The spec requires date-times to adhere to RFC3339

**Comment by dmitrizagidulin** [comment]
+1, will change over to RFC3339.

**Comment by dmitrizagidulin** [comment]
Next steps: @dmitrizagidulin to address this week.

**Comment by aljones15** [comment]
fixed this can not push to this repo.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #64, closing.
