### ISSUE TITLE
Missing copyright

### ISSUE THREAD

**Issue by aljones15** [w3c/vc-test-suite#23]
Files are not copyrighted

sorry for the nit pick =)
Apparently the copyright is needed for open source standards.
util.js has no copyright etc.

**Comment by dmitrizagidulin** [comment]
@aljones15 Thanks, will add!

**Comment by dmitrizagidulin** [comment]
Next steps: @dmitrizagidulin to fix today.

**Comment by dmitrizagidulin** [comment]
Closed via PR #60.
