### ISSUE TITLE
README directions are incorrect

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-test-suite#29]
The README directions for submitting an implementation report have some errors.
`4. Rename implementation/results.json to implementation/YOUR_IMPLEMENTATION-results.json.`
should be:
`4. Rename implementations/report.json to implementations/YOUR_IMPLEMENTATION-report.json.`

`5. git add implementations/YOUR_IMPLEMENTATION-results.json and submit a pull request for your implementation.`
should be:
`5. git add implementations/YOUR_IMPLEMENTATION-report.json and submit a pull request for your implementation.`

And it is unclear what the purpose of this instruction is:
`6. cd implementations/ && node generate.js`

**Comment by dmitrizagidulin** [comment]
Thanks for the catch, re typo. This'll be fixed along with the fix to issue #14.

(The purpose of step 6, `node generate.js` is to convert the report.json into html of the implementation report page)

**Comment by dmitrizagidulin** [comment]
Fixed by PR #33.
