### ISSUE TITLE
Report is non-specific in its categorization of tests

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-test-suite#30]
The auto-generated report.json document only has *passed* and *failed* as results from tests. This is regardless of whether a MUST or a MAY was tested, or whether the feature was implemented or not implemented.
If my implementation does not provide `@context` it **does not** conform to the VC spec.
If my implementation does not provide `expirationDate` it **does** conform to the VC spec.
However, both of those reports would only indicate failure. There is nothing in the report to differentiate between the 'failure' of an optional element test (e.g., for MAY, SHOULD, RECOMMENDED), and the 'failure' of an essential element test (e.g., for MUST).

**Comment by ken-ebert** [comment]
I would add that the test report should indicate "not-implemented" separately from "failed".

**Comment by dmitrizagidulin** [comment]
+1, agreed. As discussed in this past Tues call, this will be refactored to split the suites into more specific categories (VC vs VP, required vs optional, etc)

**Comment by dmitrizagidulin** [comment]
Next steps: @dmitrizagidulin and Andrew Jones will address this week.

**Comment by dmitrizagidulin** [comment]
@brentzundel Ok, so, this should now be addressed in PR https://github.com/w3c/vc-test-suite/pull/64 . Please give the `refactor` branch a test run when you have a chance.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #64, closing.
