### ISSUE TITLE
Contained verifiable credential in a verifiable presentation is missing context.

### ISSUE THREAD

**Issue by ken-ebert** [w3c/vc-test-suite#31]
In example-8.jsonld, the embedded verifiable credential contains no context. If the presentation validation software validates each embedded credential, the validation will fail.

> "verifiableCredential": [{
>    "id": "http://example.edu/credentials/3732",

would become something like

> "verifiableCredential": [{
>    "@context": [
>    "https://www.w3.org/2018/credentials/v1",
>    "https://www.w3.org/2018/credentials/examples/v1"
>    ],
>    "id": "http://example.edu/credentials/3732",

**Comment by dmitrizagidulin** [comment]
@ken-ebert Excellent question.

This is on purpose. The general JSON-LD convention is that - embedded graphs (such as the verifiableCredentials) inherit the context of the outer envelope. So, presentation validation software will need to take the @context from the outer presentation.

**Comment by dmitrizagidulin** [comment]
(This should be discussed further.)

**Comment by dlongley** [comment]
We should have VC processors reject the VCs inside a VP if `@context` is not present. It must be present.

If someone wants to run a JSON-LD processor and compact a VP (which will remove `@context` in an embedded VC) -- they may do so, but if they want that VP to be interoperable in the VC ecosystem, they must add the `@context` property back to the VCs within the VP. As a general principle, I think the burden should be on people that run external transformation tools (for whatever reason) to transform the data back into the expected VC data model format before passing it off to a VC library (as opposed to, for example, a general JSON-LD data library).

**Comment by dmitrizagidulin** [comment]
Fixed by PR #37, closing.
