### ISSUE TITLE
ZKP verifiable credential

### ISSUE THREAD

**Issue by yancyribbens** [w3c/vc-test-suite#44]
How should the verifier know if a derived zkp verifiable credential is missing a credentialSchema as opposed to a non derived verifiable credential that does not require credentialSchema?

**Comment by brentzundel** [comment]
> How should the verifier know if a derived zkp verifiable credential is missing a credentialSchema as opposed to a non derived verifiable credential that does not require credentialSchema?

For a derived zkp verifiable credential, the signature scheme may require additional information in order for a verifier to process it. The `credentialSchema` property is the standard way to provide this additional information. If it is absent, the verifier will not be able to process the credential signature.
If the verifier knows how to process the type of signature in a credential, they will also know if additional information is necessary for that processing, and will know to look for a `credentialSchema` property to find that information.

Does this answer your question?

**Comment by yancyribbens** [comment]
Somewhat.  Is it true that [example-1.jsonld](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-1.jsonld) is valid because it doesn't have a proof["signature"] and also doesn't contain `credentialSchema`, however [example-015-zkp-bad-no-credential-schema-id.jsonld](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-015-zkp-bad-no-credential-schema-id.jsonld) is invalid because it contains `proof["signagture"]` and does not contain `credentialSchema`.

**Comment by dmitrizagidulin** [comment]
From today's VCWG call:

One way to tell when the `credentialSchema` property is required is -- look at the `type` field in the `proof` section. If the type is a ZKP type (like the anon credential one), then the schema is required.
