### ISSUE TITLE
Passing tests against the testsuite are not correctly summarized in the report

### ISSUE THREAD

**Issue by ken-ebert** [w3c/vc-test-suite#59]
https://w3c.github.io/vc-test-suite/implementations/#conformance-testing-results
does not seem to include all the tests my implementation passed.
Only 1 of 9 ZKP tests shows as passing even though the implementation passed all ZKP tests at the last run of the tests.

**Comment by dmitrizagidulin** [comment]
Next steps: fix HTML generation to reflect.

**Comment by dmitrizagidulin** [comment]
@ken-ebert  This should now be addressed in PR https://github.com/w3c/vc-test-suite/pull/64 . Please give the `refactor` branch a test run when you have a chance.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #64, closing.
