### ISSUE TITLE
Add key/legend for test statuses

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-test-suite#70]
Add key/legend section for test results (check, X, untested, etc)

**Comment by dmitrizagidulin** [comment]
Added in PR #90, closing.

**Comment by TallTed** [comment]
Also commented on #90 ... probably better here.

> This is helpful ... but I wonder whether it could quickly be done (and communicate better overall) as a 2-column table? So the result column key looks exactly like the result column, complete with background color, etc.
