### ISSUE TITLE
how to deference example context

### ISSUE THREAD

**Issue by yancyribbens** [w3c/vc-test-suite#8]
test-suite input files contain example [contexts](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-1.jsonld#L4) that don't resolve.  when producing the credential, [type
](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-1.jsonld#L7) is dependant on the example context.  How should the producer dereference in a way that will pass the test-suit?

**Comment by BigBlueHat** [comment]
These should be expressed somewhere (at least in the test suite, if not as an appendix in the spec) such that an implementer can see both what an example context looks like, and how to use it within the testing framework.

**Comment by yancyribbens** [comment]
@dmitrizagidulin is this something you can help with?

**Comment by yancyribbens** [comment]
The [context](https://www.w3.org/2018/credentials/examples/v1) now resolves.
