### ISSUE TITLE
Wrong content type and CORS headers not set

### ISSUE THREAD

**Issue by yancyribbens** [w3c/vc-test-suite#9]
I believe the content type is wrong for the required context: `https://w3.org/2018/credentials/v1`.  [Example test suite file](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-1.jsonld) failes to load using the [json-ld playground](https://json-ld.org/playground/)

**Comment by davidlehn** [comment]
You should be using this:
https://www.w3.org/2018/credentials/v1
Seems the non-www redirect isn't working via CORS.
That example won't process correctly since the other "example" context URL doesn't actually exist.

**Comment by yancyribbens** [comment]
Thanks,  i'll put in a PR to fix: https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-1.jsonld#L3 for example.

Even though not including www does fix some issues by not redirecting, I think the content type should still be fixed.

**Comment by yancyribbens** [comment]
PR to use `www` to avoid redirect is here: https://github.com/w3c/vc-test-suite/pull/10

**Comment by dmitrizagidulin** [comment]
Addressed by merged PR #10.

**Comment by dlongley** [comment]
We need this header added at a minimum:

```
Access-Control-Allow-Origin: *
```

https://annevankesteren.nl/2012/12/cors-101

And I *think* that's it wrt to addressing the CORS issue.

**Comment by burnburn** [comment]
@burnburn to ask @ashimura about status.

**Comment by dlongley** [comment]
This appears to be resolved:

```
curl -I https://www.w3.org/2018/credentials/v1
HTTP/2 200 
date: Tue, 13 Aug 2019 14:46:13 GMT
content-type: application/ld+json
last-modified: Tue, 13 Aug 2019 14:10:44 GMT
etag: "5d52c4e4-1e07"
access-control-allow-origin: *
expires: Tue, 13 Aug 2019 14:56:13 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: B5FE:4DDF:765912:AC4ABA:5D52CD33
content-length: 7687
accept-ranges: bytes
via: 1.1 varnish
age: 0
x-served-by: cache-jfk8120-JFK
x-cache: MISS
x-cache-hits: 0
x-timer: S1565707574.695532,VS0,VE15
vary: Accept-Encoding
x-fastly-request-id: d29055a709963a838a244097b58fd7373ce66903
strict-transport-security: max-age=15552000; includeSubdomains; preload
content-security-policy: upgrade-insecure-requests
```
